# Generated by Django 3.0.8 on 2020-07-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupant',
            name='email',
        ),
    ]
