# Generated by Django 3.0.8 on 2020-07-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodApp', '0002_remove_occupant_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.RemoveField(
            model_name='post',
            name='occupant',
        ),
        migrations.DeleteModel(
            name='Neighbourhood',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
