# Generated by Django 3.0.8 on 2020-07-19 16:48

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodApp', '0003_auto_20200719_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [36.82, -1.29], 'marker_color': 'blue'})),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(blank=True, map_id='map')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodApp.Admin')),
                ('occupants', models.ManyToManyField(related_name='occupant', to='neighbourhoodApp.Occupant')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodApp.Neighbourhood')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodApp.Occupant')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=300)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodApp.Neighbourhood')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=300)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodApp.Neighbourhood')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
    ]
