# Generated by Django 3.0.8 on 2020-07-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodApp', '0004_amenity_business_neighbourhood_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
