# Generated by Django 3.0.8 on 2020-07-20 06:34

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbourhoodApp', '0005_auto_20200720_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='occupants',
        ),
        migrations.RemoveField(
            model_name='post',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='post',
            name='occupant',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Neighbourhood',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
