# Generated by Django 3.0.8 on 2020-07-20 21:10

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbourhoodApp', '0008_auto_20200721_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('occupants', models.IntegerField(default=1)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [36.82, -1.29], 'marker_color': 'blue'})),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(blank=True, map_id='map')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodApp.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Profile Picture')),
                ('home', mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [36.82, -1.29], 'marker_color': 'blue'})),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodApp.Neighbourhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodApp.Neighbourhood')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodApp.Occupant')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('definition', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [36.82, -1.29], 'marker_color': 'blue'})),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodApp.Neighbourhood')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('police', 'Police Post'), ('hospital', 'Hospital/Healthcare center')], max_length=50)),
                ('contact', models.CharField(max_length=100)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [36.82, -1.29], 'marker_color': 'blue'})),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodApp.Neighbourhood')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
    ]
